"""FastAPI application factory."""

from __future__ import annotations

import logging
import re
import time
import uuid
from collections.abc import AsyncIterator, Awaitable, Callable, Sequence
from contextlib import asynccontextmanager

import httpx
from fastapi import FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware

from app import __version__
from app.config import Settings, get_settings
from app.deps import AppState, RateLimiter
from app.errors import register_error_handlers
from app.logging_conf import configure_logging
from app.models import HealthResponse, HealthSources, VerifyResponse
from app.routers import hadith, prayer
from app.services.cache import TTLCache
from app.services.chat import ChatService
from app.services.daily import DailyService
from app.services.llm import LLM, OpenAILLM
from app.services.prayer import PrayerService
from app.services.verify import VerifyService
from app.sources.aladhan import AladhanClient
from app.sources.base import HadithSource
from app.sources.dorar import DorarSource
from app.sources.offline import OfflineSixBooksSource

logger = logging.getLogger("app")

_SAFE_REQUEST_ID = re.compile(r"^[A-Za-z0-9._-]{8,64}$")

DESCRIPTION = """
**تصحيح (Tashih)** — خدمة للتحقق من الأحاديث: ترسل نص الحديث فتحصل على **الحكم، ومن حكم عليه، والمصدر**.

* The ruling always comes from the data source (Dorar / the six books dataset). It is never
  generated by the LLM; `verdict_code` is computed by deterministic code.
* When a text is not found with confidence the API answers `not_found` and declines to rule.
* All errors use one envelope: `{"error": {"code", "message_ar", "message_en", "request_id"}}`.
* Enum values are lowercase strings; clients must tolerate unknown values. Changes within `/v1`
  are additive only.
"""


def build_sources(settings: Settings, client: httpx.AsyncClient) -> list[HadithSource]:
    sources: list[HadithSource] = []
    for name in settings.source_names:
        if name == "dorar":
            sources.append(
                DorarSource(
                    base_url=settings.dorar_base_url,
                    timeout=settings.dorar_timeout_seconds,
                    retry_backoff=settings.dorar_retry_backoff_seconds,
                )
            )
        elif name == "offline":
            sources.append(
                OfflineSixBooksSource(
                    client,
                    data_dir=settings.offline_data_dir,
                    base_url=settings.offline_base_url,
                    download_timeout=settings.offline_download_timeout_seconds,
                )
            )
        else:
            logger.warning("unknown source ignored", extra={"source": name})
    return sources


def create_app(
    settings: Settings | None = None,
    *,
    sources: Sequence[HadithSource] | None = None,
    llm: LLM | None = None,
    http_client: httpx.AsyncClient | None = None,
    prayer_service: PrayerService | None = None,
) -> FastAPI:
    """Build the app. ``sources`` / ``llm`` / ``http_client`` are injectable for tests."""
    settings = settings or get_settings()
    configure_logging(settings.log_level)

    @asynccontextmanager
    async def lifespan(app: FastAPI) -> AsyncIterator[None]:
        client = http_client or httpx.AsyncClient(
            timeout=httpx.Timeout(settings.dorar_timeout_seconds),
            limits=httpx.Limits(max_connections=20),
        )
        active_llm = llm
        owned_llm: OpenAILLM | None = None
        if active_llm is None and settings.openai_api_key:
            owned_llm = OpenAILLM(
                api_key=settings.openai_api_key,
                model=settings.openai_model,
                timeout=settings.openai_timeout_seconds,
            )
            active_llm = owned_llm

        active_sources = list(sources) if sources is not None else build_sources(settings, client)
        cache: TTLCache[VerifyResponse] = TTLCache(
            max_entries=settings.cache_max_entries, ttl_seconds=settings.cache_ttl_seconds
        )
        offline = next((s for s in active_sources if isinstance(s, OfflineSixBooksSource)), None)
        verify = VerifyService(
            active_sources,
            active_llm,
            cache,
            primary_rule=settings.dorar_primary_rule,
            sahihayn=offline,
        )
        app.state.tashih = AppState(
            settings=settings,
            verify=verify,
            chat=ChatService(verify, active_llm),
            rate_limiter=RateLimiter(settings.rate_limit_per_minute),
            prayer=prayer_service
            or PrayerService(
                AladhanClient(
                    client,
                    base_url=settings.aladhan_base_url,
                    timeout=settings.aladhan_timeout_seconds,
                ),
                default_method=settings.prayer_default_method,
            ),
            daily=DailyService(offline),
        )
        app.state.llm_enabled = active_llm is not None
        for source in active_sources:
            await source.start()
        logger.info(
            "startup complete",
            extra={"sources": [s.name for s in active_sources], "llm": active_llm is not None},
        )
        try:
            yield
        finally:
            for source in active_sources:
                await source.close()
            if owned_llm is not None:
                await owned_llm.close()
            if http_client is None:
                await client.aclose()
            logger.info("shutdown complete")

    app = FastAPI(
        title="Tashih API — تصحيح",
        version=__version__,
        description=DESCRIPTION,
        lifespan=lifespan,
    )
    origins = settings.cors_origin_list
    app.add_middleware(
        CORSMiddleware,
        allow_origins=origins,
        allow_credentials="*" not in origins,
        allow_methods=["GET", "POST", "OPTIONS"],
        allow_headers=["*"],
        expose_headers=["X-Request-ID", "Retry-After"],
    )

    @app.middleware("http")
    async def request_context(
        request: Request, call_next: Callable[[Request], Awaitable[Response]]
    ) -> Response:
        incoming = request.headers.get("X-Request-ID", "")
        request_id = incoming if _SAFE_REQUEST_ID.match(incoming) else str(uuid.uuid4())
        request.state.request_id = request_id
        started = time.perf_counter()
        response = await call_next(request)
        response.headers["X-Request-ID"] = request_id
        if request.url.path != "/health":
            logger.info(
                "request",
                extra={
                    "request_id": request_id,
                    "method": request.method,
                    "path": request.url.path,
                    "status": response.status_code,
                    "duration_ms": round((time.perf_counter() - started) * 1000, 1),
                },
            )
        return response

    register_error_handlers(app)
    app.include_router(hadith.router)
    app.include_router(prayer.router)

    @app.get(
        "/health",
        response_model=HealthResponse,
        tags=["system"],
        summary="حالة الخدمة / Service health",
    )
    async def health(request: Request) -> HealthResponse:
        state: AppState = request.app.state.tashih
        statuses = {s.name: s.health() for s in state.verify.sources}
        dorar = statuses.get("dorar", "disabled")
        offline = statuses.get("offline_six_books", "disabled")
        usable = dorar in ("ok", "unknown") or offline == "ready"
        return HealthResponse(
            status="ok" if usable else "degraded",
            version=__version__,
            sources=HealthSources(dorar=dorar, offline=offline),
            llm_enabled=bool(request.app.state.llm_enabled),
        )

    return app


def app_factory() -> FastAPI:
    """Entry point for ``uvicorn app.main:app_factory --factory``."""
    return create_app()
